language: node_js
node_js:
  - stable
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - indev
before_install: npm install -g grunt-cli eslint
install: npm install
before_script: grunt --dev